swagger: '2.0'
info:
  title: CRM Gateway Config
  description: API Gateway mapping for CRM API
  version: 1.0.0
schemes:
  - https
paths:
  /api/v1/promotions/promotions/list:
    post:
      summary: "List Promotions"
      operationId: listPromotions
      x-google-backend:
        address: https://crm-api-768989935757.us-central1.run.app/api/v1/promotions/promotions/list
      responses:
        '200':
          description: A successful response

  /api/v1/collections/collections/list:
    post:
      summary: "List Collections"
      operationId: listCollections
      x-google-backend:
        address: https://crm-api-768989935757.us-central1.run.app/api/v1/collections/collections/list
      responses:
        '200':
          description: A successful response
